name: Docker Build

on:
    push:
        branches: [ release ]
    pull_request:
        branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check the code
        uses: actions/checkout@v1
      -
        name: Push code
        run: |
            echo "${{ secrets.DOCKERPW }}" | docker login -u "stephen10121" --password-stdin
            docker build -t stephen10121/horizionlandscaping:1.0 .
            docker tag stephen10121/horizionlandscaping:1.0 stephen10121/horizionlandscaping:prod
            docker push stephen10121/horizionlandscaping:prod